# Generated by Django 3.2.4 on 2021-06-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210616_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='login',
        ),
    ]
